language: java

# The default JDK is 7 if unspecified, and we need 8
jdk:
  - oraclejdk8

# By default, the Travis container-based mode runs jdk1.8.0_31 (which is too old for this build)
addons:
  apt:
    packages:
    - oracle-java8-installer

# These files changes at every build, and should not be cached
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache Gradle's dependencies and wrapper download
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/