os: linux
language: java
jdk: oraclejdk8

# By default, the Travis container-based mode runs jdk1.8.0_31 (which is too old for this build)
addons:
  apt:
    packages:
    - oracle-java8-installer

#env:
#  - USE_FRAMEBUFFER=true
#  - USE_FRAMEBUFFER=false _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true
#-Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

#before_install:
#  - if [ $USE_FRAMEBUFFER = "true" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

script:
#- ./gradlew test -Dheadless=true
- ./gradlew shadowJar

# These files changes at every build, and should not be cached
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache Gradle's dependencies and wrapper download
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/